name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Pre-release tag (defaults to branch name)"
        required: false
        type: string
        default: ""
      type:
        description: "Release type (prerelease or snapshot)"
        required: false
        type: choice
        options:
          - snapshot
          - prerelease
        default: "snapshot"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base
      - run: pnpm build --filter=./packages/*

      - name: Set pre-release tag
        id: set-tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "PRE_TAG=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          else
            echo "PRE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Create Release Pull Request or Publish
        if: github.event_name != 'workflow_dispatch'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Pre-release
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.type }}" = "prerelease" ]; then
            # For prerelease
            pnpm changeset pre enter ${{ env.PRE_TAG }}
            pnpm changeset version
            pnpm changeset publish --tag ${{ env.PRE_TAG }}
          else
            # For snapshot releases
            pnpm changeset version --snapshot ${{ env.PRE_TAG }}
            pnpm changeset publish --tag ${{ env.PRE_TAG }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
